# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users_avatars/default.png', upload_to='users_avatars')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('favorite_position', models.CharField(blank=True, choices=[(b'LW', b'Left Winger'), (b'C', b'Center'), (b'D', b'Defenceman'), (b'RW', b'Right Winger'), (b'G', b'Goaltender')], max_length=2)),
                ('about', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
