# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160430_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(upload_to=b'gallery/gallery_covers'),
        ),
    ]
