# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20160430_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.CharField(choices=[(b'Too many man on ice', b'TMM'), (b'Hooking', b'HK'), (b'Tripping', b'TR'), (b'High stick', b'HS'), (b'Kneeing', b'KN'), (b'Interference', b'INT')], max_length=50)),
                ('penalty_minutes', models.PositiveSmallIntegerField()),
                ('penalty_time', models.TimeField(default=b'00:00')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='team.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='team.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team')),
            ],
        ),
    ]
