# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_auto_20160601_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='match',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='online',
            name='match',
        ),
        migrations.RemoveField(
            model_name='event',
            name='online',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='match',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='match',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Online',
        ),
    ]
