# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_auto_20160601_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 6, 1, 14, 41, 52, 953000))),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('guest_score', models.PositiveSmallIntegerField(default=0)),
                ('ot', models.CharField(blank=True, choices=[(b'OT', b'Overtime'), (b'SO', b'Shootout')], max_length=2)),
                ('match_ended', models.BooleanField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='team.Team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='team.Team')),
                ('season', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Match')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='team.Online'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penalty',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='team.Match'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('date', 'home'), ('date', 'guest')]),
        ),
    ]
