# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0023_auto_20160601_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='guest_players',
            field=models.ManyToManyField(related_name='guest_players', to='team.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_players',
            field=models.ManyToManyField(related_name='home_players', to='team.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 6, 2, 0, 25, 39, 509000)),
        ),
    ]
