# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160430_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default=1, upload_to=gallery.models.get_photo_image_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.models.get_photo_image_path),
        ),
    ]
