# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160430_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(upload_to=b'gallery_covers'),
        ),
    ]
