# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20160409_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=1, upload_to=b'teams_logos'),
            preserve_default=False,
        ),
    ]
