# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_alive',
            field=models.BooleanField(),
        ),
    ]
