# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Match')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='online',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Online'),
        ),
    ]
