# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
